# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-26 10:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('text', models.CharField(max_length=1000)),
                ('color', models.CharField(choices=[('A1D490', 'green'), ('90C3D4', 'blue'), ('D4A190', 'red'), ('EAFF96', 'yellow'), ('FFFFFF', 'white')], max_length=7)),
                ('pubdate', models.DateTimeField(verbose_name='date published')),
            ],
        ),
    ]
